mainConfig:
  type: esbuild
  path: esbuild.main.config.ts
  src: src/main/main.ts
  output:
    dir: dist/main
    filename: main.js
rendererConfig:
  type: esbuild
  path: esbuild.renderer.config.ts
  html: src/renderer/index.html
  src: src/renderer/index.tsx
  output:
    dir: dist/renderer
    filename: index.js
