mainConfig:
  type: esbuild
  path: esbuild.main.config.js
  src: src/main/main.js
  output: dist/main
rendererConfig:
  type: esbuild
  path: esbuild.renderer.config.js
  html: src/renderer/index.html
  src: src/renderer/index.jsx
  output: dist/renderer
