mainConfig:
  type: esbuild
  path: esbuild.main.config.js
  src: src/main/main.js
  output:
    dir: dist/main
    filename: main.js
rendererConfig:
  type: esbuild
  path: esbuild.renderer.config.js
  html: src/renderer/index.html
  src: src/renderer/index.jsx
  output:
    dir: dist/renderer
    filename: index.js
