mainConfig:
  type: esbuild
  path: esbuild.main.config.ts
  src: src/main/main.ts
  output: dist/main
rendererConfig:
  type: vite
  path: src/renderer/vite.config.ts
  src: src/renderer/index.tsx
  output: dist/renderer
