mainConfig:
  type: esbuild
  path: esbuild.main.config.js
  src: src/main/main.js
  output:
    dir: dist/main
    filename: main.js
rendererConfig:
  type: vite
  path: src/renderer/vite.config.js
  src: src/renderer/index.jsx
  output:
    dir: dist/renderer
