mainConfig:
  type: esbuild
  path: esbuild.main.config.js
  src: src/main/main.js
  output: dist/main
rendererConfig:
  type: vite
  path: src/renderer/vite.config.js
  src: src/renderer/index.jsx
  output: dist/renderer
