mainConfig:
  type: esbuild
  path: esbuild.config.ts
  src: src/main/main.ts
  output: dist/main
rendererConfig:
  type: webpack
  path: webpack.config.ts
  src: src/renderer/index.tsx
  output: dist/renderer
