name: CI

on:
  push:
    paths:
      - 'packages/**/src/**.ts'
      - 'packages/**/src/**.mts'
      - 'packages/**/src/**.mjs'
      - 'packages/**/src/**.js'
      - 'packages/**/src/**.json'
      - '.github/workflows/**.yml'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Lint
        run: pnpm -r lint
      - name: Build
        run: pnpm -r prepublishOnly
