name: CI

on:
  push:
    paths:
      - 'src/**.ts'
      - 'scripts/**.js'
      - '.github/workflows/**.yml'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            ~/.npm
          key: "${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}"
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Dependencies
        run: npm ci
      - name: 'Lint'
        run: npm run lint
      - name: 'tsc'
        run: npx tsc
      - name: 'Build'
        run: npm run build
